name: Build Snake APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel \
          openjdk-11-jdk unzip git build-essential libffi-dev \
          libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
          libncurses5 pkg-config
        pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-apk
        path: bin/*.apk
        compression-level: 0
