name: Build Snake APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel \
          openjdk-11-jdk unzip git build-essential libffi-dev \
          libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev
        pip install buildozer cython==0.29.33

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer android debug

    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
